#!/bin/sh
#
#  display rho_l data from a feff8 run to STDOUT in a format suitable
#  for gnuplot
# uses sed
#
# This file is part of EASE, the EXAFS Analysis System for Emacs
#
sed "1,/rho_3/s/^ /# /" $1
